### ISSUE TITLE
command prompt window 

### ISSUE THREAD

**Issue by garo50** [PUASummerOfCode/PUASRG#3]
There is a command prompt window that appears with every startup. if it was closed the program will exit.

**Comment by computeristgeek** [comment]
tried http://stackoverflow.com/questions/764631/how-to-hide-console-window-in-python
?

**Comment by garo50** [comment]
i did it :smile:

**Comment by computeristgeek** [comment]
fixed by 72485afc945299e37df1e9d2259cd5d872ec59fc
